export {
  parseExcludePaths,
  filterExcludedPaths,
  isPathExcluded,
  normalizeDirPath,
  mapLocalUploadToRemoteFiles,
  mapLocalFolderToRemoteFiles,
  scanTargetPath,
  scanGitlabTargetPath,
  replaceDirectory,
  replaceGitlabDirectory,
  replaceGitlabDirectoryDirect,
  scanGitlabTargetPathFromContext,
  replaceGitlabDirectoryFromContext,
} from '../path-replace/index.js';
